questions = {
    "Marca temporal": "timestamp",
    "Nombre de usuario": "publicIdentifier",
    "¿Cuál es tu nombre completo? ": "fullName",
    "Por favor, proporciona tu matrícula de la UAM (opcional)  ": "studentId",
    "¿Cuál es tu correo electrónico actual? (Si tienes más de uno, por favor divídelos con comas)": "email",
    " ¿En qué trimestre y año ingresaste a la UAM?  ": "admissionDate",
    "¿Cuentas con un perfil en LinkedIn? Si es así, por favor ingresa tu usuario o URL.  ": "linkedinProfile",
    "En caso de necesitar más información para el estudio, ¿podemos volver a contactarte?": "contactPermission",
    "¿Cuántos años te tomó terminar créditos, SS, PT, inglés y obtener el título?": "yearsToGraduate",
    "Si no terminaste la licenciatura en el tiempo establecido (en los trimestres previstos), ¿cuál consideras que fue el principal factor que influyó en tu retraso?  ": "delayReason",
    "En caso de otro, argumenta tu respuesta, con palabras clave": "delayReasonOther",
    "¿Cómo se llamó tu proyecto terminal? ": "thesisTitle",
    "¿Con cuál de los siguientes docentes realizaste tu Proyecto de Titulación (PT)? (Selecciona de la lista de docentes que han estado en la UAM)": "thesisAdvisor",
    "Si tu profesor no se encuentra en la lista, ¿podrías indicar su nombre?  ": "thesisAdvisorOther",
    "¿En cuál de las siguientes áreas se desarrolló tu (PT)?": "thesisArea",
    "Si no aparece en la lista, por favor especifica el área": "thesisAreaOther",
    "¿Tu (PT) estaba enfocado en el ámbito de...?": "thesisFocus",
    "¿Consideras que tu (PT) aportó algo al desarrollo de tu vida profesional? ": "thesisContribution",
    "¿Tu Servicio Social (SS) lo realizaste en el ámbito…?": "socialServiceArea",
    "En caso de ser interno, ¿En cuál de las siguientes áreas se desarrolló tu Servicio Social (SS)? ": "socialServiceAreaInternal",
    "Si no aparece en la lista, por favor especifica el área.1": "socialServiceAreaInternalOther",
    "¿Tu (SS) estaba enfocado en el ámbito de...?": "socialServiceFocus",
    "¿Consideras que tu (SS) aportó algo al desarrollo de tu vida profesional? ": "socialServiceContribution",
    "¿Consideras que el nivel académico que exige la UAM es adecuado y suficiente para desarrollarte en el ámbito profesional? ": "academicLevel",
    "¿Por qué?  ": "academicLevelReason",
    "¿Con qué nivel de inglés ingresaste a la licenciatura? (Selecciona tu nivel de entre los siguientes)": "englishLevel",
    "¿Con qué nivel de inglés egresaste de la licenciatura? (Selecciona tu nivel de entre los siguientes)  ": "englishLevelGraduation",
    "¿Trabajaste durante tus estudios?": "workDuringStudies",
    "¿Estaba relacionado con la carrera?": "workRelatedToMajor",
    "¿Por cuánto tiempo? ": "workDuration",
    "¿Tuviste ayuda para redactar tu primer CV?": "helpWithFirstCV",
    "¿Consideras que sería importante incluir un taller de desarrollo de CV?": "cvWorkshopImportant",
    "¿Conoces la modalidad de recibirse por experiencia laboral?": "knowsWorkExperienceGraduation",
    "Respecto a las UEA optativas, ¿cuáles consideras que te han ayudado más en tu formación como profesionista?": "helpfulOptativeCourses",
    "¿Qué temas consideras que te faltaron por abarcar en las UEA optativas durante tu formación? ": "missingOptativeTopics",
    "Al concluir tus estudios de licenciatura, ¿continuaste con estudios de posgrado?": "continuedPostgraduate",
    "En caso de que realizaste un posgrado. \n¿En qué área están o estuvieron enfocados tus estudios de posgrado?  ": "postgraduateArea",
    "En caso de que realizaste un posgrado. \n¿Consideras que tus estudios de posgrado te ayudaron a conseguir un mejor puesto de trabajo?  ": "postgraduateHelpedJob",
    "¿Has participado en algún otro programa que te haya ayudado a complementar tus estudios de licenciatura? (Por ejemplo, diplomados, congresos, cursos, etc.)  ": "otherComplementaryStudies",
    "¿En cuál de las siguientes áreas están o estuvieron enfocados estos estudios adicionales? (Por ejemplo, diplomados, congresos, cursos, etc.) ": "complementaryStudiesAreas",
    "Desde que concluiste tus estudios de licenciatura, ¿estás laborando o has laborado en algo relacionado con tu licenciatura? ": "workingInField",
    "¿Cuánto tiempo te tardaste en encontrar un empleo relacionado con tu licenciatura? ": "timeToFindJob",
    "¿Cuántos empleos has tenido desde que concluiste tus estudios, relacionados con tu licenciatura? ": "numberOfJobs",
    "Del siguiente listado de habilidades transversales, ¿cuáles consideras que posees y que además te han ayudado en tu formación como profesionista?\n\n(Selecciona todas las que apliquen)  ": "transversalSkills",
    "Del siguiente listado de habilidades transversales, ¿qué habilidades consideras que te hicieron falta desarrollar durante tu formación en la UAM?\n\n(Selecciona todas las que apliquen)  ": "missingTransversalSkills",
    "Del siguiente listado de habilidades disciplinares, ¿cuáles consideras que posees y que además te han ayudado en tu formación como profesionista?\n\n(Selecciona todas las que apliquen)": "disciplinarySkills",
    "Del siguiente listado de habilidades disciplinares, ¿qué habilidades consideras que te hicieron falta desarrollar durante tu formación en la UAM?\n\n(Selecciona todas las que apliquen)": "missingDisciplinarySkills",
    "Como Computólogo, ¿qué habilidades consideras que te diferencian de profesionistas de otras áreas? ": "differentiatingSkills",
    "Durante tu estancia en la licenciatura, ¿realizaste alguna de las siguientes actividades extracurriculares?\n(Selecciona todas las que apliquen)\n": "extracurricularActivities",
    "En caso de haber seleccionado 'Otro', por favor argumenta tu respuesta con palabras clave que describan la actividad extracurricular que realizaste.": "otherExtracurricularActivities",
    "¿Consideras que participar (o, en su defecto, de haber participado) en estas actividades extracurriculares aportaron a tu desarrollo profesional?": "extracurricularContribution",
    "¿Por qué?": "extracurricularContributionReason",
    "El próximo año, la licenciatura cumple 20 años. ¿Estarías interesado/a en participar en un evento para conmemorar los 20 años? ": "interested20thAnniversary"
}
